# Generated by Django 5.2.17 on 2026-09-29 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EntreprisesApp', '0001_initial'),
        ('ExpeditionsApp', '0001_initial'),
        ('VehiculesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_proposition', models.DateField(auto_now_add=True)),
                ('delai_jours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('statut', models.CharField(choices=[('proposee', 'proposee'), ('acceptee', 'acceptee'), ('refusee', 'refusee'), ('retirée', 'retirée')], default='proposee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='EntreprisesApp.entreprise')),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='ExpeditionsApp.expedition')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='VehiculesApp.vehicule')),
            ],
        ),
    ]
